# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.7
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: himanshumalik0069@gmail.com
author_name: Himanshu Malik
contract_name: contract_pigeon
preset_name: starter
project_name: Pigeon-Contract

